[package]
name = "madsim-fs"
version = "0.1.0"
edition = "2021"

[dependencies]
madsim = {version =  "0.2.31" }
snap-buf = "0.4.0"
atomic_refcell="0.1.13"
tokio = { version = "1.43.0",features = ["fs"] }